name: ddnotify
description: Desktop Notifications library for Dart.
version: 0.1.0
homepage: https://github.com/pti/ddnotify

environment:
  sdk: '>=2.8.0-dev <3.0.0'

dependencies:
  ddbus:
    git:
      url: https://github.com/pti/ddbus
      ref: 49334f87353e3164eefd1ac7d480b17dd1b03abf

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
